services:

  mongo:
    image: mongo:7
    container_name: journal-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    image: ryansumitha/journal-app:latest
    container_name: journal-app
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/journaldb
    ports:
      - "8080:8080"

volumes:
  mongo-data: